/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.crud.ProductsCRUD;
import model.storedProcedure.SPProducts;

/**
 *
 * @author Usuario
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        productos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(productos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void showProducts(){
        DefaultTableModel model = (DefaultTableModel) productos.getModel();
        List<ProductsCRUD> products = new SPProducts().consultProducts();
        try{
            model.addRow(new Object[]{"Código", "Nombre", "Tipo", 
                "Descripción", "Precio", "Código Almacen"});
            
            for(ProductsCRUD i : products){
                model.addRow(new Object[]{
                i.getCodigo(),
                i.getNombre(),
                i.getTipo(),
                i.getDescripcion(),
                i.getPrecio(),
                i.getCodigoAlmacen()});
            }
            
            productos.setModel(model);
            add(productos);
        }catch(Exception ex){
            JOptionPane.showMessageDialog(productos, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable productos;
    // End of variables declaration//GEN-END:variables
}
