/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Connection.ConnectDB;
import model.crud.ProductsCRUD;
import model.crud.VentasCRUD;

/**
 *
 * @author Cristo
 */
public class Ventas extends javax.swing.JPanel {
    private String ID;
    /**
     * Creates new form Clientess
     */
    public Ventas() {
        initComponents();
        insertjComboBoxCodigoProdcuto();
        insertjComboBoxIdClient();
        insertjComboBoxdniUser();
        mostrarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        fondo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaVentas = new javax.swing.JTable();
        campoCantidadProducto = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBorrar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxIDCliente = new javax.swing.JComboBox<>();
        jComboBoxCodigoProducto = new javax.swing.JComboBox<>();
        jComboBoxDniUsuario = new javax.swing.JComboBox<>();
        jSeparator5 = new javax.swing.JSeparator();
        campoIdVenta = new javax.swing.JTextField();

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondo.setBackground(new java.awt.Color(230, 251, 255));
        fondo.setForeground(new java.awt.Color(153, 153, 153));

        tablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Cantidad producto", "Precio Total", "DNI Usuario", "Codigo Prodcuto", "Id Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaVentas.setSelectionBackground(new java.awt.Color(230, 251, 255));
        tablaVentas.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVentasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaVentas);

        campoCantidadProducto.setBackground(new java.awt.Color(230, 251, 255));
        campoCantidadProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campoCantidadProducto.setForeground(new java.awt.Color(0, 148, 174));
        campoCantidadProducto.setText("Ingrese Cantidad Producto");
        campoCantidadProducto.setBorder(null);
        campoCantidadProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCantidadProductoMouseClicked(evt);
            }
        });
        campoCantidadProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCantidadProductoActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 148, 174));

        jSeparator4.setBackground(new java.awt.Color(0, 148, 174));

        jPanel1.setBackground(new java.awt.Color(0, 159, 193));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        btnInsertar.setBackground(new java.awt.Color(0, 159, 193));
        btnInsertar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInsertar.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnInsertar.setText("INSERTAR");
        btnInsertar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 159, 193));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        btnBorrar.setBackground(new java.awt.Color(0, 159, 193));
        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBorrar.setText("BORRAR");
        btnBorrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBorrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBorrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 159, 193));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        btnActualizar.setBackground(new java.awt.Color(0, 159, 193));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnActualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActualizarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 159, 193));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        btnBuscar.setBackground(new java.awt.Color(0, 159, 193));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnBuscar.setText("BUSCAR");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 159, 193));
        jPanel6.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setBackground(new java.awt.Color(0, 159, 193));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESTABLECER");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(0, 159, 193));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 159, 193));
        jLabel6.setText("Ventas");

        jComboBoxIDCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIDClienteActionPerformed(evt);
            }
        });

        jComboBoxCodigoProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxDniUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jSeparator5.setBackground(new java.awt.Color(0, 148, 174));

        campoIdVenta.setBackground(new java.awt.Color(230, 251, 255));
        campoIdVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        campoIdVenta.setForeground(new java.awt.Color(0, 148, 174));
        campoIdVenta.setText("Ingrese Id Venta");
        campoIdVenta.setBorder(null);
        campoIdVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoIdVentaMouseClicked(evt);
            }
        });
        campoIdVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoLayout = new javax.swing.GroupLayout(fondo);
        fondo.setLayout(fondoLayout);
        fondoLayout.setHorizontalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(campoCantidadProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addGroup(fondoLayout.createSequentialGroup()
                                .addComponent(jSeparator4)
                                .addGap(307, 307, 307))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxIDCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCodigoProducto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxDniUsuario, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5)
                            .addComponent(campoIdVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        fondoLayout.setVerticalGroup(
            fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(fondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(fondoLayout.createSequentialGroup()
                        .addComponent(campoCantidadProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxIDCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jComboBoxCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jComboBoxDniUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(campoIdVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );

        jPanel2.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIDClienteActionPerformed

    }//GEN-LAST:event_jComboBoxIDClienteActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        limpiar();
        mostrarTabla();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        String idVenta = campoIdVenta.getText();
        
        if(idVenta.equals("Ingrese Id Venta")){
            JOptionPane.showMessageDialog(null, "Debe introducir id para poder hacer una búsqueda ");
        }else{
            Connection con = new ConnectDB().getConetion();
            limpiar();
            mostrarTablaBusqueda(idVenta); 
        }
        
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnActualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActualizarMouseClicked
         VentasCRUD venta = new VentasCRUD();
        if(campoCantidadProducto.getText().matches("^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$")){
            if(!campoCantidadProducto.getText().isEmpty())
            venta.setProductLot(Integer.parseInt(campoCantidadProducto.getText()));
            else JOptionPane.showMessageDialog(null, "Tiene que insertar un valor en "
                + "cantidad de producto", "ERROR", JOptionPane.WARNING_MESSAGE);
        }else JOptionPane.showMessageDialog(null, "Introduca un dato valido en "
            + "el cantidad de producto", "ERROR Tipo", JOptionPane.WARNING_MESSAGE);
        venta.modify(Integer.parseInt(campoIdVenta.getText()));
        
        limpiar();
        mostrarTabla();
    }//GEN-LAST:event_btnActualizarMouseClicked

    private void btnBorrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBorrarMouseClicked
        VentasCRUD productos = new VentasCRUD();
        productos.delete(Integer.parseInt(campoIdVenta.getText()));
        
        limpiar();
        mostrarTabla();
    }//GEN-LAST:event_btnBorrarMouseClicked

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        int cantidadProducto = 0;
        String codProduct = jComboBoxCodigoProducto.getSelectedItem().toString();
        System.out.println(codProduct);
        String IdClient = jComboBoxIDCliente.getSelectedItem().toString();
        String dniUser = this.jComboBoxDniUsuario.getSelectedItem().toString();
        if(campoCantidadProducto.getText().matches("^[+-]?([0-9]+([.][0-9]*)?|[.][0-9]+)$")){
            try {
                cantidadProducto = Integer.parseInt(campoCantidadProducto.getText());
                VentasCRUD venta = new VentasCRUD(cantidadProducto, dniUser, codProduct, IdClient);
                venta.insert();
                limpiar();
                mostrarTabla();
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(null, e.toString());
                limpiar();
            }
        }else JOptionPane.showMessageDialog(null, "Introduca un dato valido en "
            + "el cantidad de producto", "ERROR Tipo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void campoCantidadProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCantidadProductoActionPerformed

    }//GEN-LAST:event_campoCantidadProductoActionPerformed

    private void campoCantidadProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCantidadProductoMouseClicked
        campoCantidadProducto.setText("");
    }//GEN-LAST:event_campoCantidadProductoMouseClicked

    //Esto nos permitirá seleccionar una fila directamente en la tabla y que se rellenen los campos
    private void tablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVentasMouseClicked
        try {
            //Variable apra saber que fila se está seleccionando
            int fila = tablaVentas.getSelectedRow();
            //Variable que conttenga el ID de la fila seleccionada
            String Id = tablaVentas.getValueAt(fila, 0).toString();

            //Establecer conexion
            Connection con = new ConnectDB().getConetion();

            //Insertar campos
            PreparedStatement ps;
            ResultSet rs;
            ps = con.prepareStatement("select CantidadProducto from Ventas where Id_Venta=?");
            ps.setString(1, Id);
            rs = ps.executeQuery();

            //Recorremos resultado de la consulta y establecemos los valores a los campos correspondientes
            while(rs.next()){
                campoCantidadProducto.setText("CantidadProducto");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }//GEN-LAST:event_tablaVentasMouseClicked

    private void campoIdVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdVentaActionPerformed

    private void campoIdVentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoIdVentaMouseClicked
        campoIdVenta.setText("");
    }//GEN-LAST:event_campoIdVentaMouseClicked
    
    private void insertjComboBoxCodigoProdcuto(){
        List<String> codigo = new ArrayList<>();
        try(Connection CONNECT = new ConnectDB().getConetion();
                Statement stm = CONNECT.createStatement();){
            String consult = "SELECT codigo FROM Productos";
            ResultSet rs  = stm.executeQuery(consult);
            
            jComboBoxCodigoProducto.removeAllItems();
            
            while(rs.next()){
                codigo.add(rs.getString("codigo"));
            }
                
            rs.close();
            stm.close();
            CONNECT.close();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        codigo.forEach((i) -> { jComboBoxCodigoProducto.addItem(i);});
    }
    
    private void insertjComboBoxIdClient(){
        List<String> id = new ArrayList<>();
        try(Connection CONNECT = new ConnectDB().getConetion();
                Statement stm = CONNECT.createStatement();){
            String consult = "SELECT Id FROM Clientes";
            ResultSet rs  = stm.executeQuery(consult);
            
            jComboBoxIDCliente.removeAllItems();
            
            while(rs.next()){
                id.add(rs.getString("Id"));
            }
                
            rs.close();
            stm.close();
            CONNECT.close();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        id.forEach((i) -> { jComboBoxIDCliente.addItem(i);});
    }
    //Metodo que nos permitirá limpiar los campos: ID, NOMBRE, DIRECCION, ETC
    private void limpiar(){
        campoCantidadProducto.setText("Ingrese Cantidad de Producto");
        campoIdVenta.setText("Ingrese Id Venta");
    }
    
    private void insertjComboBoxdniUser(){
        List<String> dni = new ArrayList<>();
        try(Connection CONNECT = new ConnectDB().getConetion();
                Statement stm = CONNECT.createStatement();){
            String consult = "SELECT dni FROM Usuarios";
            ResultSet rs  = stm.executeQuery(consult);
            
            jComboBoxDniUsuario.removeAllItems();
            
            while(rs.next()){
                dni.add(rs.getString("dni"));
            }
                
            rs.close();
            stm.close();
            CONNECT.close();
        }catch(SQLException ex){
            ex.printStackTrace();
        }
        dni.forEach((i) -> { jComboBoxDniUsuario.addItem(i);});
    }
    //Metodo que nos permitirá limpiar los campos: ID, NOMBRE, DIRECCION, ETC
 
    
     //Metodo para mostrar tabla
    private void mostrarTabla(){
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
     
        //Nos agrega diseño directamente desde el Panel, usando la tabla creada. Evitando así hacer todo el diseño manualmente
        DefaultTableModel dtm = (DefaultTableModel) tablaVentas.getModel();
        //Al poner la cuenta a 0 conseguimos que la información no se repita, sino que se reinicie
        dtm.setRowCount(0);
        
        try {
            Connection con = new ConnectDB().getConetion();
            ps = con.prepareStatement("select Id_Venta, CantidadProducto, PrecioTotal, DNI_Empleado, codigo_producto, id_cliente from Ventas");
            rs = ps.executeQuery();
            
            //Nos permite obtener los metadatos de la consulta para asi obtener la cantidad de columnas de la tabla
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            //Obtener datos de consulta
            while(rs.next()){
                //Aquí podemos ver para que nos ibamos a necesitar la variable columnas.
                //Con ella le daremos un tamño al array
                Object [] fila = new Object [columnas];
                for (int i=0; i<columnas; i++){
                    fila[i] = rs.getObject(i+1);
                }
                dtm.addRow(fila);
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    
    //Método para mostrar tabla tras Busqueda
    private void mostrarTablaBusqueda(String id){
        PreparedStatement ps;
        ResultSet rs;
        ResultSetMetaData rsmd;
        int columnas;
        
        //Nos agrega diseño directamente desde el Panel, usando la tabla creada. Evitando así hacer todo el diseño manualmente
        DefaultTableModel dtm = (DefaultTableModel) tablaVentas.getModel();
        //Al poner la cuenta a 0 conseguimos que la información no se repita, sino que se reinicie
        dtm.setRowCount(0);
        
        try {
            Connection con = new ConnectDB().getConetion();
            ps = con.prepareStatement("select Id_Venta, CantidadProducto, PrecioTotal, DNI_Empleado, codigo_producto, id_cliente from Ventas where Id_Venta = ?");
            
            ps.setString(1, id);
            rs = ps.executeQuery();
            
            //Nos permite obtener los metadatos de la consulta para asi obtener la cantidad de columnas de la tabla
            rsmd = rs.getMetaData();
            columnas = rsmd.getColumnCount();
            
            //Obtener datos de consulta
            while(rs.next()){
                //Aquí podemos ver para que nos ibamos a necesitar la variable columnas.
                //Con ella le daremos un tamño al array
                Object [] fila = new Object [columnas];
                for (int i=0; i<columnas; i++){
                    fila[i] = rs.getObject(i+1);
                }
                dtm.addRow(fila);
            }
            
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.toString());
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnActualizar;
    private javax.swing.JLabel btnBorrar;
    private javax.swing.JLabel btnBuscar;
    private javax.swing.JLabel btnInsertar;
    private javax.swing.JTextField campoCantidadProducto;
    private javax.swing.JTextField campoIdVenta;
    private javax.swing.JPanel fondo;
    private javax.swing.JComboBox<String> jComboBoxCodigoProducto;
    private javax.swing.JComboBox<String> jComboBoxDniUsuario;
    private javax.swing.JComboBox<String> jComboBoxIDCliente;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable tablaVentas;
    // End of variables declaration//GEN-END:variables
}
